CREATE TABLE `case_law` (
	`id` int AUTO_INCREMENT NOT NULL,
	`caseNumber` varchar(50),
	`year` int NOT NULL,
	`entityNameArabic` varchar(300),
	`entityNameEnglish` varchar(300) NOT NULL,
	`entityType` enum('ministry','government_company','municipality','public_authority','other') DEFAULT 'other',
	`violationType` enum('embezzlement','bribery','conflict_of_interest','abuse_of_power','forgery','tender_violation','administrative_negligence','other') NOT NULL,
	`violationTypeArabic` varchar(200),
	`violationTypeEnglish` varchar(200),
	`accusedPosition` varchar(200),
	`accusedPositionArabic` varchar(200),
	`legalArticles` text,
	`sentenceYears` int,
	`sentenceMonths` int,
	`fineOMR` int,
	`amountInvolved` int,
	`amountRecovered` int,
	`additionalPenalties` text,
	`summaryArabic` text,
	`summaryEnglish` text,
	`detailsArabic` text,
	`detailsEnglish` text,
	`outcome` enum('convicted','acquitted','pending','settled') DEFAULT 'convicted',
	`sourceReport` varchar(100),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `case_law_id` PRIMARY KEY(`id`)
);
